{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusion-bff.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fusion-bff.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.secret.oidcClientSecret | quote }}
  SESSION_SECRET: {{ .Values.secret.sessionSecret | quote }}
{{- end }}
